import { GoogleGenAI } from "@google/genai";
import { GeneratedContent } from "../types";

const API_KEY = process.env.API_KEY || '';

if (!API_KEY) {
  console.error("API_KEY is missing from environment variables.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

/**
 * Edits an image based on a text prompt using Gemini 2.5 Flash Image.
 * 
 * @param base64Data The raw base64 string of the image (without the data:image/xxx;base64, prefix if possible, but the SDK handles inlineData objects).
 *                   However, for cleaner handling, we usually pass the raw bytes.
 *                   If the input string includes the prefix, we strip it.
 * @param mimeType The mime type of the image (e.g., 'image/png').
 * @param prompt The text instruction for editing.
 */
export const editImageWithGemini = async (
  base64Data: string,
  mimeType: string,
  prompt: string
): Promise<GeneratedContent> => {
  try {
    // Strip the data URL prefix if present to get just the base64 data
    const cleanBase64 = base64Data.replace(/^data:image\/\w+;base64,/, "");

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      // Note: responseMimeType and responseSchema are NOT supported for nano banana series models.
      // We rely on the model returning an image part.
    });

    let generatedImage: string | undefined;
    let generatedText: string | undefined;

    // Check candidates for content
    if (response.candidates && response.candidates.length > 0) {
      const parts = response.candidates[0].content.parts;
      
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
           // Create a usable data URL for the frontend
           generatedImage = `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        } else if (part.text) {
          generatedText = part.text;
        }
      }
    }

    if (!generatedImage && !generatedText) {
      throw new Error("No content generated by the model.");
    }

    return {
      imageUrl: generatedImage,
      text: generatedText
    };

  } catch (error) {
    console.error("Error generating content:", error);
    throw error;
  }
};
